version: 2.1

orbs:
  colony: quali/cloudshell-colony@dev:first
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/SmartBear-ServiceVirtualization
    steps:
      - checkout
      - run:
          name: Archive app
          command: |
            mkdir -p workspace
            tar -zcf workspace/leads-webapp.latest.tar.gz -C sample_app/ .
      - persist_to_workspace:
          root: workspace
          paths:
            - leads-webapp.latest.tar.gz

  publish:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/copy:
          from: /tmp/workspace/leads-webapp.latest.tar.gz
          to: "s3://leads-webapp-artifacts/latest/"
workflows:
  leadeasy:
    jobs:
      - build
      - publish:
          requires:
            - build 
      - colony/sandbox:
          sandbox-name: "test-sandbox"
          blueprint: "leadeasy-application"
          inputs: "{'AWS_INSTANCE_TYPE': 'm5.large'}"
          artifacts: "{'leadeasy-frontend':'latest/leads-webapp.latest.tar.gz','salesforce-virt':'sf-virtual-service/leads-virt.war'}"
          steps:
            - run: echo "${SANDBOX_DETAILS}"
          requires:
            - publish
